---
- name: Restart SSH Service
  import_tasks: restart_ssh.yml

- name: Restart fail2ban Service
  import_tasks: restart_fail2ban.yml

- name: Restart ufw Service
  import_tasks: restart_ufw.yml

- name: Restart syslog-ng Service
  import_tasks: restart_syslog.yml

- name: Restart NTP Service
  import_tasks: restart_ntp.yml
...