---
allowed_in_tcp:
  - port: 22
  - port: 25
  - port: 80
  - port: 443

allowed_in_udp:
  - port: 51820

custom_rules:
  - "-N WIREGUARD"
  - "-A FORWARD -j WIREGUARD"
  - "-A WIREGUARD -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT"
  - "-A WIREGUARD -i wg0 -j ACCEPT"
  - "-A WIREGUARD -j RETURN"
...

