---
#- name: Install Software
#  import_tasks: install_software.yml
#  when: ansible_facts['os_family']|lower == 'debian'

- name: Copy sshd_config
  import_tasks: cp_sshd_config.yml

- name: Copy UFW apps
  import_tasks: cp_ufw_apps.yml

- name: Setup fail2ban
  import_tasks: setup_fail2ban.yml
...