---
- name: Install Software
  import_tasks: install_software.yml
  tags: install

- name: Setup SSH
  import_tasks: setup_ssh.yml
  tags: ssh

# - name: Setup UFW
#   import_tasks: setup_ufw.yml
#   tags: ufw

- name: Setup fail2ban
  import_tasks: setup_fail2ban.yml
  tags: fail2ban

- name: Setup syslog
  import_tasks: setup_syslog.yml
  tags: syslog

- name: Setup NTP
  import_tasks: setup_ntp.yml
  tags: ntp

- name: Setup IPTABLES
  import_tasks: setup_iptables.yml
  tags: iptables
...