---
- name: Create timesyncd config directory
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    mode: '0755'

- name: Generate ntp config
  become: yes
  ansible.builtin.template:
    src: ntp-base.j2
    dest: /etc/systemd/timesyncd.conf.d/ntp-base.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart NTP Service
...