---
#- name: Print OS architecture
#  ansible.builtin.debug:
#    var: ansible_facts['architecture']

- name: Generate OTEL basic config
  become: yes
  ansible.builtin.template:
    src: otel-base.j2
    dest: /etc/otelcol-contrib/config.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart OTEL Service
  when:
    # Only for ARMv7 and Intel architecture. No OTEL collector available for ARMv6
    - ansible_facts['architecture'] == "aarch64" or ansible_facts['architecture'] == "x86_64"
...