---
- name: Generate OTEL basic config
  become: yes
  ansible.builtin.template:
    src: otel-base.j2
    dest: /etc/otelcol-contrib/config.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart OTEL Service
  when:
    - ansible_facts['architecture'] == "aarch64"
...