---
- name: Render iptables template
  ansible.builtin.template:
    src: rules.v4.j2
    dest: /tmp/rules.v4
    #notify:
    #  - Apply iptables rules

  #handlers:
  #  - name: Apply iptables rules
  #    ansible.builtin.shell:
  #      cmd: "iptables-restore < rules.v4"
  #    changed_when: false
...