---
- name: Add basic firewalld services to public zone
  become: yes
  ansible.posix.firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ firewalld_services }}"

- name: Add custom firewalld services to public zone
  become: yes
  ansible.posix.firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ custom_firewalld_services }}"
  when:
    - custom_firewalld_services is defined

- name: Add default network interface to zone public
  become: yes
  ansible.posix.firewalld:
    zone: public
    interface: "{{ ansible_default_ipv4.interface }}"
    permanent: true
    state: enabled
  notify:
    - Restart firewalld Service
...

